import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import './globals.css'
import Home from './pages/Home.page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <Header />
      <Sidebar />

      <Home />

      <body className={inter.className}>{children}</body>
    </html>
  )
}
